<?php

/**
 * Copyright 2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */
?>

<script type="text/javascript">
  //<![CDATA[
  function validateCredentials() {
    var marketplace = $('amazon_mcf_credentials_marketplace').value;
    var sellerId = $('amazon_mcf_credentials_seller_id').value;
    var accessKeyId = $('amazon_mcf_credentials_access_key_id').value;
    var secretAccessKey = $('amazon_mcf_credentials_secret_access_key').value;

    new Ajax.Request('<?php echo $this->getAjaxValidateUrl() ?>', {
      method:     'get',
      parameters: {
        marketplace: marketplace,
        seller_id: sellerId,
        access_key_id: accessKeyId,
        secret_access_key: secretAccessKey
      },
      onSuccess: function(response){

        if (response.responseJSON){
          $('credentials_validate_result').update(response.responseJSON.message);
        }
      }
    });
  }
  //]]>
</script>

<?php echo $this->getButtonHtml() ?>

<div id="credentials_validate_result"></div>
